-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.completion_states
    ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated can read"
    ON public.completion_states
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.role() = 'authenticated'::text));

CREATE POLICY "owners can execute all"
    ON public.completions
    AS PERMISSIVE
    FOR ALL
    TO public
    USING (can_write_completions(profile_id()))
    WITH CHECK (can_write_completions(profile_id()));

DROP POLICY IF EXISTS "completions - owners can execute ALL " ON public.completions;
