-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public.tags_objectives FROM authenticated;
REVOKE ALL ON TABLE public.tags_objectives FROM postgres;
REVOKE ALL ON TABLE public.tags_objectives FROM service_role;
GRANT ALL ON TABLE public.tags_objectives TO authenticated;

GRANT ALL ON TABLE public.tags_objectives TO service_role;

GRANT ALL ON TABLE public.tags_objectives TO postgres;

ALTER TABLE IF EXISTS public.games_users DROP COLUMN IF EXISTS user_id;

REVOKE ALL ON TABLE public.games_boards FROM authenticated;
REVOKE ALL ON TABLE public.games_boards FROM postgres;
REVOKE ALL ON TABLE public.games_boards FROM service_role;
GRANT ALL ON TABLE public.games_boards TO authenticated;

GRANT ALL ON TABLE public.games_boards TO service_role;

GRANT ALL ON TABLE public.games_boards TO postgres;

REVOKE ALL ON TABLE public.boards_completions FROM authenticated;
REVOKE ALL ON TABLE public.boards_completions FROM postgres;
REVOKE ALL ON TABLE public.boards_completions FROM service_role;
GRANT ALL ON TABLE public.boards_completions TO authenticated;

GRANT ALL ON TABLE public.boards_completions TO service_role;

GRANT ALL ON TABLE public.boards_completions TO postgres;

REVOKE ALL ON TABLE public.games_objectives FROM authenticated;
REVOKE ALL ON TABLE public.games_objectives FROM postgres;
REVOKE ALL ON TABLE public.games_objectives FROM service_role;
GRANT ALL ON TABLE public.games_objectives TO authenticated;

GRANT ALL ON TABLE public.games_objectives TO service_role;

GRANT ALL ON TABLE public.games_objectives TO postgres;

REVOKE ALL ON TABLE public.boards FROM authenticated;
REVOKE ALL ON TABLE public.boards FROM postgres;
REVOKE ALL ON TABLE public.boards FROM service_role;
GRANT ALL ON TABLE public.boards TO authenticated;

GRANT ALL ON TABLE public.boards TO service_role;

GRANT ALL ON TABLE public.boards TO postgres;
