-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.games
(
    id uuid NOT NULL,
    label character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    board_size smallint NOT NULL DEFAULT '5'::smallint,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT games_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.games
    OWNER to postgres;

ALTER TABLE IF EXISTS public.games
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.games TO anon;

GRANT ALL ON TABLE public.games TO authenticated;

GRANT ALL ON TABLE public.games TO postgres;

GRANT ALL ON TABLE public.games TO service_role;

COMMENT ON TABLE public.games
    IS 'The game instances';
CREATE POLICY "games - authenticated users can read"
    ON public.games
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.role() = 'authenticated'::text));

CREATE TRIGGER handle_updated_at
    BEFORE UPDATE 
    ON public.games
    FOR EACH ROW
    EXECUTE FUNCTION extensions.moddatetime('updated_at');
